/**
 * Alert Service
 *
 * Handles sending trading alerts through multiple channels:
 * - Telegram (primary)
 * - Email
 *
 * Removed: WhatsApp/SMS (Twilio) - replaced by Telegram
 */

const nodemailer = require('nodemailer');
const { config } = require('../config/config');
const { logger, logAlert } = require('../utils/logger');
const { formatTimeForAlert } = require('../utils/timeUtils');
const { formatWHYSectionHTML } = require('../engine/reasonBuilder');

// Import Telegram service
const telegramService = require('./telegramService');

// Initialize Nodemailer transporter
let emailTransporter = null;

function getEmailTransporter() {
  if (!emailTransporter) {
    emailTransporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: config.email.user,
        pass: config.email.appPassword,
      },
      connectionTimeout: 30000, // 30 seconds
      greetingTimeout: 30000,
      socketTimeout: 60000,
    });
  }
  return emailTransporter;
}

/**
 * Send Telegram message
 * @param {string} message - Message to send
 * @returns {Promise<Object>} Telegram response
 */
async function sendTelegram(message) {
  try {
    const result = await telegramService.sendMessage(message);
    logAlert('TELEGRAM', true, message.substring(0, 100));
    return result;
  } catch (error) {
    logAlert('TELEGRAM', false, error.message);
    logger.error('Telegram send failed', { error: error.message });
    throw error;
  }
}

/**
 * Send email via Nodemailer
 * @param {string} subject - Email subject
 * @param {string} body - Email body (HTML supported)
 * @returns {Promise<Object>} Nodemailer response
 */
async function sendEmail(subject, body) {
  try {
    const transporter = getEmailTransporter();
    const result = await transporter.sendMail({
      from: config.email.user,
      to: config.alerts.email,
      subject: subject,
      html: body,
      text: body.replace(/<[^>]*>/g, ''), // Strip HTML for plain text
    });
    logAlert('EMAIL', true, subject);
    return result;
  } catch (error) {
    logAlert('EMAIL', false, error.message);
    logger.error('Email send failed', { error: error.message });
    throw error;
  }
}

/**
 * Format signal into plain text alert message
 * @param {Object} signal - Trading signal object
 * @returns {string} Formatted message
 */
function formatAlertMessage(signal) {
  const {
    primaryStrategy,
    strategy,
    direction,
    strike,
    premium,
    stopLoss,
    spotPrice,
    time,
    isCDaySignal,
    confidenceScore,
    whySection,
  } = signal;

  const strategyName = primaryStrategy || strategy || 'COMBINED';
  const targetPremium = premium ? Math.round(premium * 2) : 'N/A';
  const maxRisk = config.trading.maxLossPerTrade.toLocaleString('en-IN');

  // C-Day signal warning
  const header = isCDaySignal
    ? `C-DAY SIGNAL

FORCE ANALYZE MODE
Previous day was NOT an A-Day.
Trade with extra caution.

--------------------`
    : `A-DAY SIGNAL`;

  let message = `${header}

Setup: ${strategyName}
Direction: NIFTY ${direction}

Strike: ${strike || 'TBD'}
Premium: Rs ${premium || 'TBD'}
Spot: ${spotPrice}
Time: ${formatTimeForAlert(time || new Date())}

Stop Loss: Spot ${direction === 'BUY_CE' ? 'below' : 'above'} ${stopLoss}
Target: 2x Risk (Rs ${targetPremium})
Max Risk: Rs ${maxRisk}`;

  // Add WHY section if available
  if (whySection) {
    message += `\n\n${whySection}`;
  }

  message += '\n\n---\nAuto-generated by A-Day Alert System';

  return message;
}

/**
 * Format signal into HTML email
 * @param {Object} signal - Trading signal object
 * @returns {string} HTML formatted email
 */
function formatEmailBody(signal) {
  const {
    primaryStrategy,
    strategy,
    direction,
    strike,
    premium,
    stopLoss,
    spotPrice,
    time,
    isCDaySignal,
    confidenceScore,
    reasons,
    contributingStrategies,
  } = signal;

  const strategyName = primaryStrategy || strategy || 'COMBINED';
  const targetPremium = premium ? Math.round(premium * 2) : 'N/A';
  const maxRisk = config.trading.maxLossPerTrade.toLocaleString('en-IN');

  // C-Day warning banner
  const cdayBanner = isCDaySignal ? `
  <div style="background: #fff3cd; border-left: 4px solid #ffc107; padding: 15px; margin: 15px 0;">
    <strong>FORCE ANALYZE MODE - C-DAY SIGNAL</strong><br/>
    Previous day was NOT an A-Day.<br/>
    <strong>Trade with extra caution.</strong>
  </div>
  ` : '';

  const headerColor = isCDaySignal ? '#ff9800' : '#1a73e8';
  const headerText = isCDaySignal ? 'C-DAY SIGNAL' : 'A-DAY SIGNAL';

  // Generate WHY section HTML
  const whySectionHTML = reasons && reasons.length > 0
    ? formatWHYSectionHTML(reasons, confidenceScore || 0)
    : '';

  // Contributing strategies section
  const strategiesSection = contributingStrategies && contributingStrategies.length > 0
    ? `<div style="background: #f8f9fa; padding: 15px; margin: 15px 0; border-radius: 8px;">
        <strong>Contributing Strategies:</strong> ${contributingStrategies.join(', ')}
       </div>`
    : '';

  return `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; max-width: 650px; margin: 0 auto; background: #f5f5f5; }
    .header { background: ${headerColor}; color: white; padding: 20px; text-align: center; border-radius: 8px 8px 0 0; }
    .content { padding: 20px; background: white; }
    .signal-box { background: #f5f5f5; border-left: 4px solid #1a73e8; padding: 15px; margin: 15px 0; }
    .label { color: #666; font-size: 12px; text-transform: uppercase; }
    .value { font-size: 18px; font-weight: bold; color: #333; }
    .risk { background: #fff3cd; border-left: 4px solid #ffc107; padding: 15px; margin: 15px 0; }
    .confidence { background: #d4edda; border-left: 4px solid #28a745; padding: 15px; margin: 15px 0; }
    .footer { text-align: center; color: #999; font-size: 12px; padding: 20px; border-top: 1px solid #eee; }
  </style>
</head>
<body>
  <div class="header">
    <h1 style="margin: 0;">${headerText}</h1>
    ${confidenceScore ? `<p style="margin: 10px 0 0 0; opacity: 0.9;">Confidence: ${confidenceScore}/100</p>` : ''}
  </div>
  <div class="content">
    ${cdayBanner}
    <div class="signal-box">
      <div class="label">Setup</div>
      <div class="value">${strategyName}</div>
    </div>
    <div class="signal-box">
      <div class="label">Direction</div>
      <div class="value">NIFTY ${direction}</div>
    </div>
    <div class="signal-box">
      <div class="label">Strike</div>
      <div class="value">${strike || 'TBD'}</div>
    </div>
    <div class="signal-box">
      <div class="label">Premium</div>
      <div class="value">Rs ${premium || 'TBD'}</div>
    </div>
    <div class="signal-box">
      <div class="label">Spot Price</div>
      <div class="value">${spotPrice}</div>
    </div>
    <div class="signal-box">
      <div class="label">Time</div>
      <div class="value">${formatTimeForAlert(time || new Date())}</div>
    </div>
    <div class="risk">
      <div class="label">Stop Loss</div>
      <div class="value">Spot ${direction === 'BUY_CE' ? 'below' : 'above'} ${stopLoss}</div>
    </div>
    <div class="risk">
      <div class="label">Target</div>
      <div class="value">2x Risk (Rs ${targetPremium})</div>
    </div>
    <div class="risk">
      <div class="label">Max Risk</div>
      <div class="value">Rs ${maxRisk}</div>
    </div>

    ${whySectionHTML}
    ${strategiesSection}
  </div>
  <div class="footer">
    Auto-generated by A-Day Alert System
  </div>
</body>
</html>`;
}

/**
 * Send alert through all channels (Telegram + Email)
 * @param {Object} signal - Trading signal object
 * @returns {Promise<Object>} Results from all channels
 */
async function sendAlert(signal) {
  const message = formatAlertMessage(signal);
  const emailBody = formatEmailBody(signal);
  const emailSubject = signal.isCDaySignal
    ? `C-DAY SIGNAL: ${signal.primaryStrategy || signal.strategy} - ${signal.direction}`
    : `A-DAY SIGNAL: ${signal.primaryStrategy || signal.strategy} - ${signal.direction}`;

  const results = {
    telegram: null,
    email: null,
    errors: [],
  };

  // Send all alerts in parallel
  const promises = [
    telegramService.sendAlert(signal)
      .then(r => { results.telegram = r; })
      .catch(e => { results.errors.push({ channel: 'telegram', error: e.message }); }),
    sendEmail(emailSubject, emailBody)
      .then(r => { results.email = r; })
      .catch(e => { results.errors.push({ channel: 'email', error: e.message }); }),
  ];

  await Promise.all(promises);

  const successCount = [results.telegram, results.email].filter(Boolean).length;
  logger.info('Alert sent', {
    strategy: signal.primaryStrategy || signal.strategy,
    direction: signal.direction,
    confidence: signal.confidenceScore,
    successCount,
    errors: results.errors,
  });

  return results;
}

/**
 * Send a test alert
 * @returns {Promise<Object>} Results from all channels
 */
async function sendTestAlert() {
  const testSignal = {
    primaryStrategy: 'TEST ALERT',
    strategy: 'TEST ALERT',
    direction: 'BUY_CE',
    strike: '22800 CE',
    premium: 100,
    stopLoss: 22500,
    spotPrice: 22750,
    time: new Date(),
    confidenceScore: 75,
    reasons: [
      { factor: 'Test Factor 1', status: 'pass', detail: 'This is a test reason' },
      { factor: 'Test Factor 2', status: 'neutral', detail: 'Another test reason' },
    ],
  };

  logger.info('Sending test alert');
  return sendAlert(testSignal);
}

// Legacy exports for backward compatibility
async function sendWhatsApp(message) {
  logger.warn('sendWhatsApp called but WhatsApp is disabled - using Telegram instead');
  return sendTelegram(message);
}

async function sendSMS(message) {
  logger.warn('sendSMS called but SMS is disabled - using Telegram instead');
  return sendTelegram(message);
}

module.exports = {
  sendTelegram,
  sendEmail,
  sendAlert,
  sendTestAlert,
  formatAlertMessage,
  formatEmailBody,
  // Legacy exports
  sendWhatsApp,
  sendSMS,
};
